import dotenv from 'dotenv';

dotenv.config();

export default {
  ENVIRONMENT: process.env.ENVIRONMENT || 'DEVELOPMENT',
  PORT: process.env.PORT || 3001,
  CORS: process.env.CORS || '*',
  MAX_REQUEST_RATE_LIMIT: process.env.MAX_REQUEST_RATE_LIMIT || 5,
  MAX_TIMEOUT_RATE_LIMIT: process.env.MAX_TIMEOUT_RATE_LIMIT || 15000,
  MONGO_DB_CONNECTION: process.env.MONGO_DB_CONNECTION || '',
  REDIS_DB_CONNECTION: process.env.REDIS_DB_CONNECTION || 'redis://localhost:6379',
  JWT_TOKEN_SECRET: process.env.JWT_TOKEN_SECRET || 'test',
  JWT_EXPIRATION_TIME: process.env.JWT_EXPIRATION_TIME || '2h',
  CRYPT_ROUNDS: process.env.CRYPT_ROUNDS || 10,
  TWILIO_FROM_PHONE: process.env.TWILIO_FROM_PHONE || '',
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID || '',
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN || '',
  VERIFICATION_CODE_RECOVERY_PASSWORD: process.env.VERIFICATION_CODE_RECOVERY_PASSWORD || 300,
  CRONJOB_TIME_EXECUTION: process.env.CRONJOB_TIME_EXECUTION || 5,
  PROCESS_BATCH_QUANTITY: process.env.PROCESS_BATCH_QUANTITY || '100',
  SENTRY_DSN: process.env.SENTRY_DSN || '',
  POSTGRESQL_URL: process.env.POSTGRESQL_URL || '',
};
